### ISSUE TITLE
I love it!

### ISSUE THREAD

**Issue by michaelbromley** [BrunnerLivio/brunnerlivio#2]
<div align="center">
  <img src="https://github.com/BrunnerLivio/brunnerlivio/blob/master/images/guestbook.png?raw=true" alt="Guestbook" />
  <br />
</div>

Hey Livio, this is such a throwback to my teenage years, thanks!

I'd like to see more people adopt the style and then you could complete the 90s nostalgia trip by setting up a webring.

Thanks for your work on Nestjs. Greetings from Vienna, Austria

![6qcacbmzt6w11](https://user-images.githubusercontent.com/6275952/88053555-47305100-cb5c-11ea-9613-e5cf21a7e0d9.jpg)

**Comment by BrunnerLivio** [comment]
Haha thank you @michaelbromley ! I took inspiration from @fnky, which I absolutely loved!
I'd love to see more Retro styled Github profiles, that is why I've started a Pull Request here: https://github.com/abhisheknaiidu/awesome-github-profile-readme/pull/132

**Comment by fnky** [comment]
Let the 2000s live on! Hope to see more personal pages like this. Wish GitHub allowed the use of marquee's too, to fully embrace the nostalgia!

**Comment by BrunnerLivio** [comment]
@fnky It is possible! You can use SVGs with `foreignObject` to use "rich HTML" in Markdown.
Checkout my commit here:
96970fa3082b450b3e73703dd0867f17c938dce0

Thanks @sindresorhus for bringing marquees to READMEs <3 (see tweet [here](https://twitter.com/sindresorhus/status/1285609420098088961))

**Comment by fnky** [comment]
Damn, that's cool! Thanks!
