### ISSUE TITLE
Guestbook with Github Actions

### ISSUE THREAD

**Issue by openscript** [BrunnerLivio/brunnerlivio#61]
<div align="center">
  <img src="https://github.com/BrunnerLivio/brunnerlivio/blob/master/images/guestbook.png?raw=true" alt="Guestbook" />
  <br />
</div>

**Message:**

Great Readme! :) Last night I created a "real" guestbook with Github Actions. [See](https://github.com/openscript)

**Comment by BrunnerLivio** [comment]
Oh that is amazing! Don't mind if I copy your code? :P

**Comment by openscript** [comment]
Not at all, but I would be very happy if you leave a link in your comment to my profile :dancers:

**Comment by BrunnerLivio** [comment]
@openscript Sure, done :)
